---
title: "Text Minining"
author: "Joohyun Kwon"
date: "May 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tm)
library(ggplot2)
```

load text file and sample about 10% of the text
```{r cache=TRUE}
blog = readLines('./final/en_US/en_US.blogs.txt', encoding = 'UTF-8')
set.seed(465)
blog <- sample(blog, round(length(blog)/10))
docs <- Corpus(VectorSource(blog))
```

```{r cache=TRUE}
news = readLines('./final/en_US/en_US.news.txt', encoding = 'UTF-8')
set.seed(376)
news = sample(news, round(length(news)/10)
                          
                          
```

Define a content transformer that will substitute matching pattern to single space
```{r}
toSpace = content_transformer(function(x, pattern) { return (gsub(pattern, ' ', x))})
```

replace ':' and '-' with space using above toSpace content transformer
```{r cache=TRUE}
#docs = tm_map(docs, toSpace, ':')
#docs = tm_map(docs, toSpace, '-')
#docs = tm_map(docs, toSpace, '?')
#docs = tm_map(docs, toSpace, '.')
#docs = tm_map(docs, toSpace, ';')
#docs = tm_map(docs, toSpace, ')')
#docs = tm_map(docs, toSpace, '(')
```

not removing punctuaton. will manually remove one by one. or find a way to remove in bulk. I would like to keep "'" in "don't", "I've", etc.
```{r cache=TRUE}
#docs = tm_map(docs, removePunctuation)
docs = tm_map(docs, removeNumbers)
#docs = tm_map(docs, content_transformer(tolower))
```

```{r cache=TRUE}

#docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, stripWhitespace)
```

load library for stemming
```{r}
#library(SnowballC)
```
```{r cache=TRUE}
#docs = tm_map(docs, stemDocument)
```
```{r}
dtm = DocumentTermMatrix(docs)
```



